name: Main Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  test:
    uses: hs-heilbronn-devsecops-bigpipe/note-api/.github/workflows/python-tests.yml@main